DROP TABLE IF EXISTS service_usage CASCADE;
DROP TABLE IF EXISTS money_operations CASCADE;
DROP TABLE IF EXISTS promised_payments CASCADE;
DROP TABLE IF EXISTS applications CASCADE;
DROP TABLE IF EXISTS user_data CASCADE;
DROP TABLE IF EXISTS bank CASCADE;
DROP TABLE IF EXISTS users CASCADE;

DROP TYPE IF EXISTS promised_payment_status CASCADE;
DROP TYPE IF EXISTS usage_direction CASCADE;
DROP TYPE IF EXISTS usage_type CASCADE;
DROP TYPE IF EXISTS operation_type CASCADE;
DROP TYPE IF EXISTS application_type CASCADE;
